title: "BravoXL"
author: "BravoXL"
description: "上官平川"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true        # show site description and social linls in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "MyGithub", url: "https://github.com/BravoXL"}
  - {file: "README.md",title: "Know Me"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Mail", icon: envelope, url: "zxlearly(AT)gmail.com"}
  - {title: "Github", icon: github, url: "https://github.com/BravoXL/OfficeCodes"}
 # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
